---
name: Cloud Native Transformation Muster
title: Cloud Native Transformation Muster

kramdown: 
  parse_block_html: true
permalink: /:title

collections:
  development-design:
    output: false
  infrastructure-cloud:
    output: false
  organization-culture:
    output: true
  strategy-risk-reduction:
    output: true
  operations:
    output: false

# Google Analytics
# deactivated because we don't want to mix up the statistics for German and the English version
# google_analytics: UA-53586058-2
